language: ruby
jdk:
  - openjdk6
  - oraclejdk7
rvm:
  - jruby
  - jruby-head
before_script:
  - export JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
before_install:
  - ((jruby -v | grep 1.8.7) && jruby --1.9 -S gem update --system 2.1.11) || true
env:
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
  - JRUBY_OPTS="$JRUBY_OPTS"
matrix:
  allow_failures:
    - rvm: jruby-head # until JRuby-Rack 1.1.15
  exclude:
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS"
      jdk: openjdk6
    - rvm: jruby-head
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
      jdk: openjdk6
    - rvm: jruby-head
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
      jdk: oraclejdk7