language: ruby
sudo: false
script: rake spec
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
rvm:
  - jruby-1.7.22
  - jruby-9.0.1.0
before_script:
  - export JRUBY_OPTS="-Xcompile.invokedynamic=false" # --server
  - export JAVA_OPTS="$JAVA_OPTS -Xmx600m -XX:MaxPermSize=300m"
  - echo "JAVA_OPTS=$JAVA_OPTS"
  - echo "JRUBY_OPTS=$JRUBY_OPTS"
before_install:
  - ((jruby -v | grep 1.8.7) && jruby --1.9 -S gem update --system 2.1.11) || true
  - if [[ "${TRAVIS_RUBY_VERSION:0:9}" =~ "jruby-9.0" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION; fi
env:
  - JRUBY_OPTS="$JRUBY_OPTS" # RAILS_VERSION="~> 4.2.1"
matrix:
  allow_failures:
    - rvm: jruby-1.6.8
  include:
    - rvm: jruby-1.7.22
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
      jdk: openjdk6
    - rvm: jruby-1.7.22
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
      jdk: oraclejdk7
    - rvm: jruby-1.6.8
      env: JRUBY_OPTS="$JRUBY_OPTS"
      jdk: openjdk6
    - rvm: jruby-1.6.8
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" RAILS_VERSION="~> 3.2"
      jdk: openjdk6
  exclude:
    - rvm: jruby-9.0.0.0
      env: JRUBY_OPTS="$JRUBY_OPTS"
      jdk: openjdk6
